<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=iso-8859-1" />
		<script type="text/javascript" src="http://192.168.100.2/common.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/english.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/language.js"></script>
		<link type="text/css" rel="stylesheet" href="help.css">
		<title>Help (build 40559) - Services</title>
	</head>
<body><div id="header"><div class="logo"> </div><div class="navig"><a href="index.asp">Index</a> | <a href="javascript:self.close();"><script type="text/javascript">Capture(sbutton.clos)</script></a></div></div><div id="content"><h2>Services</h2><dl><dt><script type="text/javascript">Capture(service.dhcp_legend2)</script></dt><script type="text/javascript">Capture(hservice.page1)</script><dt><script type="text/javascript">Capture(service.dnsmasq_legend)</script></dt><script type="text/javascript">Capture(hservice.page2)</script><dt><script type="text/javascript">Capture(service.kaid_legend)</script></dt><script type="text/javascript">Capture(hservice.page3)</script><script type="text/javascript">Capture(service.kaid_locdevnum)</script><script type="text/javascript">Capture(hservice.page4)</script><script type="text/javascript">Capture(service.kaid_uibind)</script><script type="text/javascript">Capture(hservice.page5)</script><dt><script type="text/javascript">Capture(service.rflow_legend)</script></dt><script type="text/javascript">Capture(hservice.page6)</script><dt><script type="text/javascript">Capture(service.ssh_legend)</script></dt><script type="text/javascript">Capture(hservice.page7)</script><dt><script type="text/javascript">Capture(service.syslog_legend)</script></dt><script type="text/javascript">Capture(hservice.page8)</script><dt><script type="text/javascript">Capture(service.telnet_legend)</script></dt><script type="text/javascript">Capture(hservice.page9)</script></dl></div><div class="also"><h4><script type="text/javascript">Capture(share.seealso)</script></h4><ul><li><a href="HSetup.asp"><script type="text/javascript">Capture(bmenu.setupbasic)</script></a></li><li><a href="HManagement.asp"><script type="text/javascript">Capture(bmenu.adminManagement)</script></a></li></ul></div></body></html>