<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=iso-8859-1" />
		<script type="text/javascript" src="http://192.168.100.2/common.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/english.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/language.js"></script>
		<link type="text/css" rel="stylesheet" href="help.css">
		<title>Help (build 40559) - Wireless Status</title>
	</head>
<body><div id="header"><div class="logo"> </div><div class="navig"><a href="index.asp">Index</a> | <a href="javascript:self.close();"><script type="text/javascript">Capture(sbutton.clos)</script></a></div></div><div id="content"><h2><script type="text/javascript">Capture(status_wireless.h2)</script></h2><dl><script type="text/javascript">Capture(hstatus_wireless.page1)</script><dt><script type="text/javascript">Capture(share.mac)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page2)</script><dt><script type="text/javascript">Capture(share.mode)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page3)</script><dt><script type="text/javascript">Capture(share.ssid)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page4)</script><dt><script type="text/javascript">Capture(share.channel)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page5)</script><dt><script type="text/javascript">Capture(wl_basic.TXpower)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page6)</script><dt><script type="text/javascript">Capture(share.rates)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page7)</script><dt><script type="text/javascript">Capture(share.encrypt)</script></dt><script type="text/javascript">Capture(hstatus_wireless.page8)</script></dl></div><div class="also"><h4><script type="text/javascript">Capture(share.seealso)</script></h4><ul><li><a href="HStatus.asp">Router Status</a></li><li><a href="HStatusLan.asp">LAN Status</a></li></ul></div></body></html>