<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=iso-8859-1" />
		<script type="text/javascript" src="http://192.168.100.2/common.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/english.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/language.js"></script>
		<link type="text/css" rel="stylesheet" href="help.css">
		<title>Help (build 40559) - Firewall</title>
	</head>
<body><div id="header"><div class="logo"> </div><div class="navig"><a href="index.asp">Index</a> | <a href="javascript:self.close();"><script type="text/javascript">Capture(sbutton.clos)</script></a></div></div><div id="content"><h2><script type="text/javascript">Capture(bmenu.firwall)</script></h2><dl><dt><script type="text/javascript">Capture(firewall.proxy)</script></dt><script type="text/javascript">Capture(hfirewall.page1)</script><dt><script type="text/javascript">Capture(firewall.cookies)</script></dt><script type="text/javascript">Capture(hfirewall.page2)</script><dt><script type="text/javascript">Capture(firewall.applet)</script></dt><script type="text/javascript">Capture(hfirewall.page3)</script><dt><script type="text/javascript">Capture(firewall.activex)</script></dt><script type="text/javascript">Capture(hfirewall.page4)</script><dt><script type="text/javascript">Capture(firewall.ping)</script></dt><script type="text/javascript">Capture(hfirewall.page5)</script><dt><script type="text/javascript">Capture(firewall.muticast)</script></dt><script type="text/javascript">Capture(hfirewall.page6)</script><dt><script type="text/javascript">Capture(filter.nat)</script></dt><script type="text/javascript">Capture(hfirewall.page7)</script><dt><script type="text/javascript">Capture(filter.port113)</script></dt><script type="text/javascript">Capture(hfirewall.page8)</script></dl><h2><script type="text/javascript">Capture(log.h2)</script></h2><dl><script type="text/javascript">Capture(hfirewall.page9)</script><dt><script type="text/javascript">Capture(log.legend)</script></dt><script type="text/javascript">Capture(hfirewall.page10)</script><dt><script type="text/javascript">Capture(log.lvl)</script></dt><script type="text/javascript">Capture(hfirewall.page11)</script><dt><script type="text/javascript">Capture(sbutton.log_in)</script></dt><script type="text/javascript">Capture(hfirewall.page12)</script><dt><script type="text/javascript">Capture(sbutton.log_out)</script></dt><script type="text/javascript">Capture(hfirewall.page13)</script></dl></div><div class="also"><h4><script type="text/javascript">Capture(share.seealso)</script></h4><ul><li><a href="HForwardSpec.asp"><script type="text/javascript">Capture(bmenu.applicationspforwarding)</script></a></li><li><a href="HDMZ.asp"><script type="text/javascript">Capture(bmenu.applicationsDMZ)</script></a></li></ul></div></body></html>