<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=iso-8859-1" />
		<script type="text/javascript" src="http://192.168.100.2/common.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/english.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/language.js"></script>
		<link type="text/css" rel="stylesheet" href="help.css">
		<title>Help (build 40559) - Port Range Forwarding</title>
	</head>
<body><div id="header"><div class="logo"> </div><div class="navig"><a href="index.asp">Index</a> | <a href="javascript:self.close();"><script type="text/javascript">Capture(sbutton.clos)</script></a></div></div><div id="content"><h2><script type="text/javascript">Capture(prforward.h2)</script></h2><dl><dd>To add a new Port Range Forwarding rule, click <i>Add</i> and fill in the fields below. To remove the last rule, click <i>Remove</i>.</dd><script type="text/javascript">Capture(hprforward.page1)</script><dt><script type="text/javascript">Capture(prforward.app)</script></dt><script type="text/javascript">Capture(hprforward.page2)</script><dt><script type="text/javascript">Capture(share.start)</script></dt><script type="text/javascript">Capture(hprforward.page3)</script><dt><script type="text/javascript">Capture(share.end)</script></dt><script type="text/javascript">Capture(hprforward.page4)</script><dt><script type="text/javascript">Capture(share.proto)</script></dt><script type="text/javascript">Capture(hprforward.page5)</script><dt><script type="text/javascript">Capture(share.ip)</script></dt><script type="text/javascript">Capture(hprforward.page6)</script><dt><script type="text/javascript">Capture(share.enable)</script></td><script type="text/javascript">Capture(hprforward.page7)</script></dl></div><div class="also"><h4><script type="text/javascript">Capture(share.seealso)</script></h4><ul><li><a href="HForwardSpec.asp"><script type="text/javascript">Capture(bmenu.applicationspforwarding)</script></a></li><li><a href="HUPnP.asp"><script type="text/javascript">Capture(bmenu.applicationsUpnp)</script></a></li><li><a href="HTrigger.asp"><script type="text/javascript">Capture(bmenu.applicationsptriggering)</script></a></li><li><a href="HDMZ.asp"><script type="text/javascript">Capture(bmenu.applicationsDMZ)</script></a></li></ul></div></body></html>