<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=iso-8859-1" />
		<script type="text/javascript" src="http://192.168.100.2/common.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/english.js"></script>
		<script type="text/javascript" src="http://192.168.100.2/lang_pack/language.js"></script>
		<link type="text/css" rel="stylesheet" href="help.css">
		<title>Help (build 40559) - UPnP</title>
	</head>
<body><div id="header"><div class="logo"> </div><div class="navig"><a href="index.asp">Index</a> | <a href="javascript:self.close();"><script type="text/javascript">Capture(sbutton.clos)</script></a></div></div><div id="content"><h2><script type="text/javascript">Capture(upnp.h2)</script></h2><dl><!--dd>Universal Plug and Play (UPnP) is a set of computer network protocols. This Microsoft technology is for automatic configuration of devices. The goals of UPnP are to allow devices to connect seamlessly and to simplify the implementation of networks in the home and corporate environments. UPnP achieves this by defining and publishing UPnP device control protocols built upon open, Internet-based communication standards.</dd--><script type="text/javascript">Capture(hupnp.page1)</script><dt><script type="text/javascript">Capture(upnp.legend)</script></dt><!--dd>The UPnP forwards table shows all open ports forwarded automatically by the UPnP process. You can delete forwards by clicking the trash can or click the <em>Delete All</em> button to clear all forwards.</dd--><script type="text/javascript">Capture(hupnp.page2)</script><dt><script type="text/javascript">Capture(upnp.serv)</script></dt><!--dd>Allows applications to automatically setup port forwardings.</dd--><script type="text/javascript">Capture(hupnp.page3)</script><dt><script type="text/javascript">Capture(upnp.clear)</script></dt><!--dd>If enabled, all UPnP port forwardings are deleted when the router starts up.</dd--></div></dd><dd>Click <i>Save Settings</i> to save your settings. Click <i>Cancel Changes</i> to cancel your unsaved changes.</dd--><script type="text/javascript">Capture(hupnp.page5)</script></dl></div><div class="also"><h4><script type="text/javascript">Capture(share.seealso)</script></h4><ul><li><a href="HManagement.asp"><script type="text/javascript">Capture(bmenu.adminManagement)</script></a></li><li><a href="HForward.asp"><script type="text/javascript">Capture(bmenu.applicationsprforwarding)</script></a></li><li><a href="HForwardSpec.asp"><script type="text/javascript">Capture(bmenu.applicationspforwarding)</script></a></li></ul></div></body></html>